services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    restart: on-failure
    stop_grace_period: 1m
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    network_mode: host
    ports: 
      - 9080:8080
