version: '3.7'

services:
  # -- THE TAILSCALE DAEMON --
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - tailscale-var-lib:/var/lib/tailscale
      - tailscale-etc:/etc/tailscale
    environment:
      - TS_AUTHKEY=tskey-auth-kMQ7FywWud11CNTRL-XdhQsPi4t4f7DYWMico15fRUbfAtJ5NrP
    command:
      - tailscaled
      - --state=/var/lib/tailscale/tailscaled.state
      - --socket=/var/run/tailscale/tailscaled.sock
    restart: on-failure

  app_proxy:
    environment:
      - APP_HOST=me-n8n-tailscaled
      - APP_PORT=5681
    restart: on-failure

  # -- THE N8N BACKEND --
  n8n_server:
    image: n8nio/n8n:latest
    container_name: n8n_server
    depends_on:
      - tailscale
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n1
    environment:
      - PUID=1000
      - PGID=1000
      - N8N_HOST=${DEVICE_DOMAIN_NAME}
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_PORT=5681
      - N8N_RUNNERS_BROKER_PORT=5680
    stop_grace_period: 1m
    restart: on-failure
    network_mode: "service:tailscale"         # ← share Tailscale network

volumes:
  tailscale-var-lib:
  tailscale-etc:
