version: '3.7'

services:
  # 1) Tailscale daemon + serve
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale_custom
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - tailscale-var-lib:/var/lib/tailscale
      - tailscale-etc:/etc/tailscale
    environment:
      - TS_AUTHKEY=tskey-auth-…
    # start tailscaled, then expose HTTP 5681 → n8n_custom:5681
    command: >
      sh -c "
        tailscaled \
          --state=/var/lib/tailscale/tailscaled.state \
          --socket=/var/run/tailscale/tailscaled.sock &
        # wait a moment for tailscaled to come up:
        sleep 2
        tailscale serve --http 5681 http://127.0.0.1:5681
      "
    restart: on-failure
    network_mode: bridge   # default bridge is fine here

  # 2) Your custom n8n instance
  n8n_custom:
    image: n8nio/n8n:latest
    container_name: n8n_custom
    depends_on:
      - tailscale
    volumes:
      - ${APP_DATA_DIR}/custom-data:/home/node/.n8n
    environment:
      - PUID=1000
      - PGID=1000
      - N8N_HOST=127.0.0.1
      - N8N_PORT=5681
      - N8N_RUNNERS_BROKER_PORT=5682
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    stop_grace_period: 1m
    restart: on-failure
    network_mode: bridge

volumes:
  tailscale-var-lib:
  tailscale-etc:
